/*              -:  NUMBER GUESSING GAME 🎮'?':-
In this game, the range is decided by the player (from 1 to n, where ‘n’ is entered by the user).
I have used a 'do-while' loop in this code because I want the loop to execute at least once, 
even if the user guesses the random number correctly on the first attempt.If the user enters a higher number, 
the if condition will execute, If the user enters a lower number, the else-if condition will execute, otherwise,
if the user enters the correct number, the else condition will execute.*/


#include<stdio.h>
#include<stdlib.h>  // This header file is used in this code to use 'srand()' function.
#include<time.h>    // This header file is used in this code to use 'time()' function.

int main(){
int n; 
printf("Enter the last number (range) :"); 
scanf("%d",&n);

srand(time(0)); //This function 'srand(time(0))' is used to make random numbers truly random.

int R_N=(rand()%n)+1; //(R_N => A random number generated by the computer up to the range n.)

int N_O_G=0;  //(N_O_G => Total number of guesses).

int G_N;   //G_N => Guessed number by user.

do{  
   printf("\nGuess the number ");
   scanf("%d",&G_N);
   if(G_N > R_N){
   printf("Your number is High please enter Lower number !");
}
else if(G_N < R_N){
printf("Your number is Low please enter Higher number");
}
else{
printf("Congrats !\n");
}
N_O_G++; //This counts how many times the user has guessed the number.  
}while(G_N != R_N);

printf("You guessed the number in %d guesses",N_O_G);
    
    return 0;
}